In [50]:
%matplotlib inline
from sklearn.model_selection import KFold
from sklearn import datasets
from sklearn import linear_model, neighbors, svm, naive_bayes

from sklearn import preprocessing
from sklearn import metrics

import numpy as np


In [16]:
kfold = KFold(n_splits=5)
kfold

KFold(n_splits=5, random_state=None, shuffle=False)

## Regressão

In [6]:
X,y = datasets.load_boston(return_X_y=True)

In [10]:
modelSGD = linear_model.SGDRegressor()
modelLR = linear_model.LinearRegression()
modelKNN = neighbors.KNeighborsRegressor()
modelSVM = svm.SVR()

In [20]:
def fazer(model,y_true, X_test, mae,rmse):
    y_pred = model.predict(X_test)
    mae += metrics.mean_absolute_error(y_true,y_pred)
    rmse += metrics.mean_squared_error(y_true,y_pred)
    return mae,rmse

In [61]:
mae1= 0.0
mae2= 0.0
mae3= 0.0
mae4 = 0.0
rmse1= 0.0
rmse2= 0.0
rmse3 = 0.0
rmse4 = 0.0

for train_index,test_index in kfold.split(X):
    X_train = X[train_index]
    y_train = y[train_index]
    X_test = X[test_index]
    y_test = y[test_index]
    
    scale = preprocessing.StandardScaler().fit(X_train)
    X_train_std = scale.transform(X_train)
    X_test_std = scale.transform(X_test)
    
    modelSGD.fit(X_train_std,y_train)
    modelLR.fit(X_train_std,y_train)
    modelKNN.fit(X_train_std,y_train)
    modelSVM.fit(X_train_std,y_train)
    
    #y_pred = model.predict(X_test)
    #mae += metrics.mean_absolute_error(y_true,y_pred)
    #rmse += metrics.mean_squared_error(y_true,y_pred)
    
    mae1,rmse1 = fazer(modelSGD,y_test,X_test_std,mae1,rmse1)
    mae2,rmse2 = fazer(modelLR,y_test,X_test_std,mae2,rmse2)
    mae3,rmse4 = fazer(modelKNN,y_test,X_test_std,mae3,rmse3)
    mae4,rmse4 = fazer(modelSVM,y_test,X_test_std,mae4,rmse4)

print("SGD- MAE: "+ str((mae1/5)) + " RMSE: "+ str(np.sqrt(rmse1/5)))
print("LR- MAE: "+ str((mae2/5)) + " RMSE: "+ str(np.sqrt(rmse2/5)))
print("KNN- MAE: "+ str((mae3/5)) + " RMSE: "+ str(np.sqrt(rmse3/5)))
print("SVM- MAE: "+ str((mae4/5)) + " RMSE: "+ str(np.sqrt(rmse4/5)))

SGD- MAE: 0.21300270141277916 RMSE: 0.26677212991217847
LR- MAE: 0.199259469258038 RMSE: 0.2534299306685874
KNN- MAE: 0.05978264244682503 RMSE: 0.0
SVM- MAE: 0.13099312174182298 RMSE: 0.11653827815920793


/home/segundo/anaconda3/lib/python3.5/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDRegressor'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


In [27]:
model = neighbors.KNeighborsRegressor()

In [29]:
scale = preprocessing.StandardScaler().fit(X)

In [40]:
X_std = scale.transform(X)
model.fit(X_std,y)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=5, p=2,
          weights='uniform')

In [41]:
y_pred = model.predict(X_std)

## Classificação

In [42]:
X,y = datasets.load_breast_cancer(return_X_y=True)

In [49]:
modelLoR = linear_model.LogisticRegression()
modelKNNC = neighbors.KNeighborsClassifier()
modelNB = naive_bayes.GaussianNB()
modelSVC = svm.SVC(probability=True)

In [63]:
def fazer2(model,y_true, X_test):
    y_pred = model.predict(X_test)
    Accuracy = metrics.accuracy_score(y_true,y_pred)
    print(metrics.confusion_matrix(y_true, y_pred))
    return Accuracy

In [64]:
Accuracy1= 0.0
Accuracy2= 0.0
Accuracy3= 0.0
Accuracy4= 0.0
#mae2= 0.0
#mae3= 0.0
#mae4 = 0.0
#rmse1= 0.0
#rmse2= 0.0
#rmse3 = 0.0
#rmse4 = 0.0

for train_index,test_index in kfold.split(X):
    X_train = X[train_index]
    y_train = y[train_index]
    X_test = X[test_index]
    y_test = y[test_index]
    
    norm = preprocessing.MinMaxScaler().fit(X_train)
    X_train_std = norm.transform(X_train)
    X_test_std = norm.transform(X_test)
    
    modelLoR.fit(X_train_std,y_train)
    modelKNNC.fit(X_train_std,y_train)
    modelNB.fit(X_train_std,y_train)
    modelSVC.fit(X_train_std,y_train)
    
    #y_pred = model.predict(X_test)
    #mae += metrics.mean_absolute_error(y_true,y_pred)
    #rmse += metrics.mean_squared_error(y_true,y_pred)
    
    Accuracy1 += fazer2(modelLoR,y_test,X_test_std)
    Accuracy2 += fazer2(modelKNNC,y_test,X_test_std)
    Accuracy3 += fazer2(modelNB,y_test,X_test_std)
    Accuracy4 += fazer2(modelSVC,y_test,X_test_std)

print("LOR- acuracy: "+ str((Accuracy1/5)))
print("KNN- acuracy: "+ str((Accuracy2/5)))
print("NB- acuracy: "+ str((Accuracy3/5)))
print("SVM- acuracy: "+ str((Accuracy4/5)))

[[58 10]
 [ 1 45]]
[[62  6]
 [ 2 44]]
[[58 10]
 [ 4 42]]
[[52 16]
 [ 0 46]]
[[42  7]
 [ 0 65]]
[[45  4]
 [ 0 65]]
[[43  6]
 [ 2 63]]
[[40  9]
 [ 0 65]]
[[36  4]
 [ 0 74]]
[[36  4]
 [ 0 74]]
[[37  3]
 [ 3 71]]
[[36  4]
 [ 0 74]]
[[28  1]
 [ 1 84]]
[[27  2]
 [ 0 85]]
[[27  2]
 [ 1 84]]
[[27  2]
 [ 0 85]]
[[26  0]
 [ 1 86]]
[[26  0]
 [ 4 83]]
[[24  2]
 [ 7 80]]
[[24  2]
 [ 1 86]]
LOR- acuracy: 0.9561248253376805
KNN- acuracy: 0.9613414066138798
NB- acuracy: 0.9296848315478963
SVM- acuracy: 0.9403043005744449


In [106]:
model = neighbors.KNeighborsClassifier()

In [107]:
norm = preprocessing.MinMaxScaler().fit(X)

In [108]:
X_norm = norm.transform(X)

In [109]:
model.fit(X_norm,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [110]:
y_pred = model.predict(X_norm)

In [111]:
a = [y_pred[i] == y[i] for i in range(0,len(y))]

In [112]:
a.count(True)

557